FROM python:3.12-slim

WORKDIR /app

COPY project app/project

RUN pip install --upgrade pip && pip install -r app/project/req.txt

VOLUME project/pictures

ENTRYPOINT ["python", "app/project/main.py"]