version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - network_exp
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1 # не секреты
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # не секреты
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092 # не секреты
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # не секреты
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # не секреты
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # не секреты
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # не секреты
    networks:
      - network_exp
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:9092" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    container_name: consumer
    image: app_init_consumer
    volumes:
      - ./logs:/app/logs:rw
    restart: always
    networks:
      - network_exp
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
      GROUP_ID: ${GROUP_ID}
      TOPIC_NAME: ${TOPIC_NAME}
    depends_on:
      - producer
    command: [ "python", "consumer.py" ]
  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    container_name: producer
    image: app_init_producer
    restart: always
    networks:
      - network_exp
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
      GROUP_ID: ${GROUP_ID}
      TOPIC_NAME: ${TOPIC_NAME}
    depends_on:
      - kafka

networks:
  network_exp:
    driver: bridge
    name: network_exp

volumes:
  logs:
