version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - network_exp
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    env_file:
      - ./.env
    networks:
      - network_exp
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:9092" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    container_name: consumer
    image: app_init_consumer
    volumes:
      - ./logs:/app/logs:rw
    restart: always
    networks:
      - network_exp
    env_file:
      - ./.env
    depends_on:
      - producer
    command: [ "python", "consumer.py" ]
  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    container_name: producer
    image: app_init_producer
    restart: always
    networks:
      - network_exp
    env_file:
      - ./.env
    depends_on:
      - kafka

networks:
  network_exp:
    driver: bridge
    name: network_exp

volumes:
  logs:
