apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  namespace: kafka
data:
  configuration: |
    akhq:
      connections:
        docker-kafka-server:
          properties:
            bootstrap.servers: "kafka-service.kafka.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:latest
        ports:
        - containerPort: 8080
        env:
        - name: AKHQ_CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: akhq-config
              key: configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: akhq-service
  namespace: kafka
  labels:
    app: akhq-service
spec:
  type: LoadBalancer
  selector:
    app: akhq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080