apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/docker/logs
  storageClassName: logs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: logs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: app_init_consumer:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: KAFKA_HOST
              value: "kafka-service.kafka.svc.cluster.local:9092"
            - name: GROUP_ID
              value: "my-group-test-1"
            - name: TOPIC_NAME
              value: "my-topic"
          volumeMounts:
            - mountPath: "/app/logs/"
              name: logs-volume
      restartPolicy: Always
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc